### PR TITLE
Update template.php

### PR DESCRIPTION
**Pull request by dcnieho**
Replaced links from svn project to github pages

### CODE REVIEW

**Comment by jtsiomb** [comment]
Don't you have acces  to commit changes directly? I need to look into permissions somewhere...

**Comment by dcnieho** [comment]
I do, but wanted a second set of eyes. I also no longer remember how to
update the website, even if i do have that access too. Will leave a note
next time ;)

**Comment by jtsiomb** [comment]
Ah ok... because I panicked and created a "maintainers team" just to make sure you have access, which was probably unnecessary :)

To update the website i have included an "upload" script in the website root directory. You can either use it directly from any UNIX-ish environment assuming you have ssh and rsync installed, or just look at it as a reminder of how it works. To use it directly you need to create a file called `.sfuser` in the same directory which contains a single line with your sourceforge username (otherwise it defaults to `$USER` in your environment).

But it's also fine with me if you'd rather poke me to upload changes. It's not as if we're updating the site all the time.

**Comment by dcnieho** [comment]
Sorry, I'll communicate better next time. Glad you have documented the process in the form of a script, that'll make this easy to do and makes sure the knowledge isn't lost. thanks!

**Pull request merged**
